# Generated by Django 4.2.7 on 2023-11-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxodecaixa',
            name='data_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fluxodecaixa',
            name='periodicidade',
            field=models.CharField(blank=True, choices=[('mensal', 'Mensal'), ('anual', 'Anual')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fluxodecaixa',
            name='recorrente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fluxodecaixa',
            name='tipo',
            field=models.CharField(choices=[('fixa', 'Fixa'), ('variavel', 'Variável'), ('renda', 'Renda'), ('despesa', 'Despesa')], max_length=8),
        ),
    ]
