# Generated by Django 4.2.7 on 2023-11-15 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoriadespesa_categoriarenda_renda_despesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FluxoDeCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('renda', 'Renda'), ('Despesa', 'Despesa')], max_length=8)),
                ('sub_tipo', models.CharField(choices=[('fixa', 'Fixa'), ('variavel', 'Variável')], max_length=8)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='categoriarenda',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='renda',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='renda',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='CategoriaDespesa',
        ),
        migrations.DeleteModel(
            name='CategoriaRenda',
        ),
        migrations.DeleteModel(
            name='Despesa',
        ),
        migrations.DeleteModel(
            name='Renda',
        ),
        migrations.AddField(
            model_name='categoria',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fluxodecaixa'),
        ),
    ]
