# Generated by Django 4.2.7 on 2023-11-15 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoria_fluxodecaixa_remove_categoriarenda_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='orcamento',
        ),
        migrations.AddField(
            model_name='fluxodecaixa',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='fluxodecaixa',
            name='tipo',
            field=models.CharField(choices=[('renda', 'Renda'), ('despesa', 'Despesa')], max_length=8),
        ),
    ]
