# Generated by Django 4.2.7 on 2023-12-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fluxodecaixa_necessidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluxodecaixa',
            name='necessidade',
            field=models.CharField(choices=[('essencial', 'Essencial'), ('desejos', 'Desejo (Não essencial)'), ('investimetos', 'Investimento')], default='essencial', max_length=12),
        ),
    ]
